boat:
  length:
    x: 2.5 # m
    y: 0.6 # m
  drag:
    water:
      C_x: 0.15
      C_y: 0.65
    air:
      C_x: 0.01
      C_y: 0.15
  CoG_Offset:
    Ix: 0.45
    Iy: 0

sail:
  main:
    drag:
      C_x: 0.1
      C_y: 0.95
  ancillary:
    drag:
      C_x: 0.1
      C_y: 0.95